name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # twice a day
  workflow_dispatch:          # manual run button
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%23F72585&color_dots=%230d1117,%237209b7,%23b026ff,%23f72585,%2300f0ff
            dist/github-snake-dark.svg?color_snake=%2300F0FF&color_dots=%230d1117,%237209b7,%23b026ff,%23f72585,%2300f0ff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
